# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

name: Open Source Software Review Toolkit (ORT)

on:
    workflow_dispatch:

    push:
        branches: [ main ]
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"

    schedule:
        # On the first day of each month at 1:30AM.
        - cron:  '30 1 1 * *'


jobs:
    oss-review-toolkit:
        runs-on: ubuntu-24.04
        steps:
            - name: "Use HTTPS instead of SSH for Git cloning"
              run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/

            - name: "Checkout repository"
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: "Run ORT GitHub Action"
              uses: oss-review-toolkit/ort-ci-github-action@9acdf1e56f1b42972b12274ae56c35bf70a5f65b # v1.01