# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>, 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

name: REUSE Compliance Check

on: [push, pull_request]


permissions:
  contents: read


jobs:
  test-reuse-compliance:
    runs-on: ubuntu-22.04

    
    steps:
    - name: "Checkout code"
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
    - name: "REUSE Compliance Check"
      uses: fsfe/reuse-action@3ae3c6bdf1257ab19397fab11fd3312144692083 # v4.0.0
